#!/usr/bin/python3

import sys
import json


dataOutput = ""

def mainFunc(input_data):

    try:
        # Load the input JSON from a string
        global dataOutput
        data = json.loads(input_data)
        step(data)
        dataOutput =  dataOutput[:-2]

        json.dump(dataOutput, sys.stdout)

    except json.JSONDecodeError as e:
        print(f"Error decoding JSON: {e}", file=sys.stderr)
        sys.exit(1)    
     
def step(data):
    global dataOutput
    if isinstance(data, str):
        dataOutput += data + ", "
    elif isinstance(data, int):
        dataOutput += "number, "
    elif isinstance(data, list):
        addList(data)
    elif isinstance(data, dict):
        addDict(data)
    elif isinstance(data, float):
        dataOutput += "number, "


def addList(data):
    for i in range(0, len(data)):
        step(data[i])

def addDict(data):
    keys = list(data.keys())
    keys.sort()

    for key in keys:
        step(data[key])


if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.exit(1)

    input_json = sys.argv[1]
    mainFunc(input_json)
